### ISSUE TITLE
Serious "batch size" regression in rocm3.5(.1)

### ISSUE THREAD

**Issue by witeko** [ROCmSoftwarePlatform/tensorflow-upstream#1027]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): ubuntu 18.04 (kernel 5.3), rhel 8.2 
- TensorFlow installed from (source or binary): 2.1, 2.2 (both "build from source" and from pypi)
- Python version: 3.6-3.8
- GPU model and memory: 2 x radeon 7
- Driver: amdgpu, 3.5-32 (used with both rocm3.3 and rocm 3.5(.1))

**Describe the current behavior**
I'm running many CNN models for image recognition. I use tensorflow. Mirrored strategy. Mixed_float16.
On 3.3 I can use reasonable batch sizes to train my networks (like 32-64).
On 3.5(.1) networks don't train (python kernel crashes with no other info). The only way to make them train is to set super low batch size like 4.

I'm having trouble in setting up both 3.3 and 3.5.1 on one system and my networks are to complex to include them here. I currently have only 3.3 - so it's difficult for me to provide You with an example. But the problem is a blocker for me..
I hope that this will raise a flag that smth is not correct and maybe You can investigate further. If absolutely necessary I am willing to invest some of me own time to help You.

**Comment by jerryyin** [comment]
This is to acknowledge that there are a number of regressions happen in ROCm 3.5 context. We have internal ticket filed to ROCm infrastructure team to track this. If your script can work with ROCm 3.3, my advise is to continue in this context. One quick way to check if you are impacted by ROCm 3.5 specific defects is to do a cross check between the disabled unit tests [here](https://github.com/ROCmSoftwarePlatform/tensorflow-upstream/pull/1009/files), and your model script. If your model script includes any of those use case, it is likely to be caused by ROCm 3.5 related regressions.

**Comment by witeko** [comment]
@jerryyin ok, thanks. :)
