### ISSUE TITLE
Compilation guide for ROCm-tensorflow needed

### ISSUE THREAD

**Issue by uswoods** [ROCmSoftwarePlatform/tensorflow-upstream#184]
I'm trying to build your software under ArchLinux (with 4.19-mainline kernel).

Which package do I need for /opt/rocm ? I've installed rocm-opencl-git and hsa-rocr.

**Comment by whchung** [comment]
@uswoods please refer to https://github.com/ROCmSoftwarePlatform/tensorflow-upstream/blob/develop-upstream/tensorflow/tools/ci_build/Dockerfile.rocm#L58 to see what ROCm packages are needed to get TensorFlow working on ROCm. Notice some of those packages are umbrella packages so additional packages would be installed.

**Comment by whchung** [comment]
@uswoods I took a brief look of what ROCm packages are there for Arch distro. And it seems there are only OpenCL runtime and lower-level ROCR runtime available. They don't constitute enough building blocks to get TensorFlow for ROCm going. Also they don't seem to be on par with the latest ROCm release (1.9).

In order to be able to build TensorFlow on ROCm, you'll likely need the following packages be built and run properly on Arch:

- KFD
- ROCR
- HCC
- HIP
- rocBLAS
- clang-ocl
- MIOpen
- rocRAND

**Comment by enihcam** [comment]
> @uswoods I took a brief look of what ROCm packages are there for Arch distro. And it seems there are only OpenCL runtime and lower-level ROCR runtime available. They don't constitute enough building blocks to get TensorFlow for ROCm going. Also they don't seem to be on par with the latest ROCm release (1.9).
> 
> In order to be able to build TensorFlow on ROCm, you'll likely need the following packages be built and run properly on Arch:
> 
> * KFD
> * ROCR
> * HCC
> * HIP
> * rocBLAS
> * clang-ocl
> * MIOpen
> * rocRAND

@whchung Can't AMD just provide a binary version of tensorflow-rocm and its runtime dependencies? please?

**Comment by sunway513** [comment]
Hi @uswoods , like @whchung suggested, tensorflow-rocm requires the full ROCm support through several software stack. Could you submit your request on [ROCm repository](https://github.com/RadeonOpenCompute/ROCm) and continue the discussion there?
