### ISSUE TITLE
tensorflow-rocm dependences on not existing version of tensorflow-intel

### ISSUE THREAD

**Issue by BaumiCoder** [ROCmSoftwarePlatform/tensorflow-upstream#2518]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

No

### Source

binary

### TensorFlow version

2.14

### Custom code

No

### OS platform and distribution

 Linux Mint 21.3 Virginia

### Python version

3.11

### Current behavior?

If I install the [tensorflow-rocm ~2.14](https://pypi.org/project/tensorflow-rocm/2.14.0.600/) package with poetry, I get an error message:
```
Because no versions of tensorflow-rocm match >=2.14,<2.14.0.600 || >2.14.0.600,<2.15
 and tensorflow-rocm (2.14.0.600) depends on tensorflow-intel (2.14.0.600), tensorflow-rocm (>=2.14,<2.15) requires tensorflow-intel (2.14.0.600).
 ```
I took a look at PyPi for the [Release History of tensorflow-intel](https://pypi.org/project/tensorflow-intel/#history) and there is only a 2.14.0 and a 2.14.1, but no 2.14.0.600. 

So there seems to be a dependency with the wrong version number in `tensorflow-rocm`.  The exact same version as the package itself have not to exist at `tensorflow-intel` :exclamation: A more vague version number (e.g., ~2.14) should be used.

### Standalone code to reproduce the issue

```shell
Installation issue, so no python code to reproduce the issue.
```

**Comment by taylding-amd** [comment]
Hi @BaumiCoder, I was not able to reproduce your error. I noticed that you are using Linux Mint 21.3 Virginia, which may cause issues as it is not a part of our [support operating system](https://rocm.docs.amd.com/projects/install-on-linux/en/latest/reference/system-requirements.html). Do you mind trying again with our [docker images](https://hub.docker.com/r/rocm/tensorflow)?

**Comment by BaumiCoder** [comment]
Linux Mint 21.3 Virginia is based on Ubuntu Jammy, so it should also work. The cause of the error is even visible in the whl file.

1. Download whl file for python 3.11 from [PyPi](https://pypi.org/project/tensorflow-rocm/2.14.0.600/#files)
2. Extract the file from the whl file
3. Open the file `tensorflow_rocm-2.14.0.600.dist-info/METADATA` with a text editor
4. Take a look at line 54:
```
Requires-Dist: tensorflow-intel (==2.14.0.600) ; platform_system == "Windows"
```
I have no idea why this line takes effect on my machine, but not at yours. However, this line reference an exact version of `tensorflow-intel` that does not exist.

I executed my experiments for a research project (bachelor thesis) in another way, so I have no need for executing with one of the docker images.

**Comment by taylding-amd** [comment]
Hi @BaumiCoder, that does appear to be a bug. Is there a specific reason you are using ROCm 6.0? I ask because, following the release of ROCm 6.1, the wheels are no longer hosted on pypi.org and can now be found at repo.radeon.com. For instance, you can access them at https://repo.radeon.com/rocm/manylinux/rocm-rel-6.2/. Would you mind trying the newer wheel file?

**Comment by BaumiCoder** [comment]
The support of my GPU was dropped with ROCm 6.1.1. All details about my try to use ROCm on the specific situation can be found [here](https://codeberg.org/BaumiCoder/Bachelorthesis/src/branch/main/Performance.md#host-1-rocm-on-amp-gpu). In the end, my quite old GPU was not powerful enough to be suitable for the task.

I take a look into the newer whl files. There is still an exact verson of `tensorflow-intel` referenced. For Example:
```
Requires-Dist: tensorflow-intel (==2.14.1) ; platform_system == "Windows"
```
If there will be again the situation that your package have some version number X.Y.600 where `tensorflow-intel` only have a version X.Y.0 or something, the problem would occur again. I do not know, how likely it is that such a case occur.

Since when, the releases had moved away from pypi.org? At the time, when I was creating this issue, I could not find the other source. Maybe you should link from the README of the package on pypi.org to your new source.

**Comment by taylding-amd** [comment]
Hi @BaumiCoder,

Thank you for bringing your concerns about the mismatched version numbers to our attention. The mismatch happened because we previously used the format `<TensorFlowVersion>.<ROCmVersion>`, but starting with version 6.1, the wheel version format has been simplified to just the TensorFlow version. From my understanding, the version number for tensorflow-intel is also aligned with TensorFlow, so mismatches are unlikely to occur.

For detailed information on wheel releases and the ROCm TensorFlow installation guide, please refer to our [official documentation](https://rocm.docs.amd.com/projects/install-on-linux/en/latest/install/3rd-party/tensorflow-install.html). You can find all ROCm-related documentation on the same website.

It appears that the bug has already been addressed in the latest releases. Is there anything else I can assist you with before we close this issue?

**Comment by BaumiCoder** [comment]
Thank you, for the clarification.
