### ISSUE TITLE
improve complex handling in cub/rocPRIM kernels

### ISSUE THREAD

**Issue by iotamudelta** [ROCmSoftwarePlatform/tensorflow-upstream#26]
complex-typed reductions currently cannot be ported to rocPRIM from cub as they use std::complex which has, on ROCm, no GPU equivalent according to rocPRIM devs ( @VincentSC ). This issue is to keep track of progress, workarounds, or possible solutions within TensorFlow.

**Comment by VincentSC** [comment]
You'd need to convert it to cuFloatComplex and hipFloatComplex, which are the GPU-versions of std::complex. See https://github.com/ROCm-Developer-Tools/HIP/blob/master/include/hip/nvcc_detail/hip_complex.h for make_hipDoubleComplex and other useful functions.

This is simply a bug in TensorFlow, which miraculously worked on Nvidia and now is triggered because ROCm has implemented it the proper way. As it did not trigger a warning when building on CUDA when there was an implicit conversion, it probably was a quick workaround that was never properly fixed.

**Comment by sunway513** [comment]
Discussed with @iotamudelta  and we are okay to close this ticket.
