### ISSUE TITLE
Tensorflow with ROCm support won't see my GPU

### ISSUE THREAD

**Issue by Shad0wSt4R** [ROCmSoftwarePlatform/tensorflow-upstream#385]
**System information**
- Ubuntu 18.10
- TensorFlow installed from source
- TensorFlow version: 2.0
- Python version: 3.6
- Installed in virtualenv with pip
- Bazel version: 0.23.0
- GCC/Compiler version: 8.2.0
- ROCm/MIOpen version: not sure. should be latest with respect to this post
- GPU model and memory: Radeon Rx 580 and 16 GB of RAM

So, I successfully built tensorflow to have ROCm support, I took a simple keras model from a tutorial online to see if I could get it to use the GPU and instead I noticed it used the CPU. I am not sure if I need to install drivers for it or not. I installed the ROCm libraries using the experimental build since I am running Ubuntu 18.10. 

When I used `./configure` I made sure to say yes to ROCm support. I also said yes to XLA JIT support. 

I compiled Tensorflow with this command:
`bazel build --config=opt --config=rocm //tensorflow/tools/pip_package:build_pip_package`

This is what I get when I run the model. It only shows CPU stats. I have used Tensorflow with an Nvidia graphics card in the past and it normally will check for the GPU and it if doesn't see it it will default to the CPU. I am not sure if the ROCm version will do that. I would like to think that it will.
![cpu_only](https://user-images.githubusercontent.com/25802539/55269067-23117800-5266-11e9-98ba-f56709962f86.png)

This is what happens when I run the `Session()` function that Tensorflow provides. It is supposed to show all mapped devices and the card doesn't seem to show up but my CPU sure does. 
![only_sees_cpu](https://user-images.githubusercontent.com/25802539/55269087-50f6bc80-5266-11e9-8d8a-454a8476e9cf.png)

I am not sure if I built it properly or not. Is there something that I could be missing?

**Comment by sunway513** [comment]
Hi @Shad0wSt4R , Ubuntu18.10 is not in ROCm2.2 support list, doc is here:
https://github.com/RadeonOpenCompute/ROCm#supported-operating-systems---new-operating-systems-available
The error you've observed might be caused by the base driver configuration.  
If you don't have plan to change your OS, you might try to upgrade your base kernel to 4.20 or newer (please review this [doc](https://github.com/RadeonOpenCompute/ROCm#rocm-support-in-upstream-linux-kernels)) and use our public docker image, e.g. the following one:
`rocm/tensorflow:rocm2.2-tf1.13-python3`
