### ISSUE TITLE
Fix CI

### ISSUE THREAD

**Issue by Bengt** [ROCmSoftwarePlatform/tensorflow-upstream#879]
These builds have been failing for months:

http://ml-ci.amd.com:21096/

They are linked in this project's README as well as the upstream TensorFlow. Therefore, visibility is quite high, making this bad look costly. Also, regular/official releases are far between and therefore lack compatibility with latest libraries at times. So stabilizing the builds continuous integration can help detect this class of errors sooner and thus drive regular releases on the library side by demonstrating their relevance to this application.

**Comment by Bengt** [comment]
The recent release of ROCm 3.1 shows that there is capability to create releases. So that knowledge needs to be collected and institutionalized in the configuration of the build server.

**Comment by ekuznetsov139** [comment]
The failing builds are for the upstream fork (tensorflow/tensorflow). CI tests for ROCmSoftwarePlatform/tensorflow-upstream consistently pass, but it takes time for our fixes to be accepted into the upstream fork, and people in charge of tensorflow/tensorflow evidently don't run the same CI as we do, so their code is rarely in a sufficiently stable condition to pass our CI.

**Comment by Bengt** [comment]
Hi @ekuznetsov139!

Thanks for the insight. I can imagine how keeping the jobs in the continuous integration succeeding is difficult with fast movement on both the side of TensorFlow and ROCmSoftwarePlatform. However, the builds have been failing for a long time, which renders them largely useless. So it would be helpful to have reasonably current builds and their artifacts readily available.

Are the CI tests for ROCmSoftwarePlatform/tensorflow-upstream public? Could badges maybe link to them in a similar fashion as the tensorflow/tensorflow's README.md? Perhaps in the community build plan?

https://github.com/ROCmSoftwarePlatform/tensorflow-upstream/blob/develop-upstream/rocm_docs/rocm-community-build-plan.md

Regards,
Bengt

**Comment by jerryyin** [comment]
It looks to me this issue has two separate concerns: 1. Existing public CI is failing frequently 2. There is no public visibility regarding the `develop-upstream` CI. 

Regarding on 1: From what I can see `tensorflow-rocm-nightly` pass rate has greatly improved in the recent period. 

Regarding on 2: @parallelo Could you remind me what the state is from the last discussion on this issue? If we have decided not to make the internal nightly CI public, please help leave a message and explain the situation here. Otherwise I can bring this up again in our weekly meeting.

**Comment by jerryyin** [comment]
We had an offline discussion at topic 2 and decided to not open internal CI. Please rely on Nightly/Stable release community supported build.
